---
version: "3.5"

# YAML pointer feature to reuse parts of the config
x-broker-common-settings: &broker-common-settings
  KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:2181'
  # listeners
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,HOST:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
  # metrics
  KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
  CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
  CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
  CONFLUENT_METRICS_ENABLE: 'true'
  # interesting features
  KAFKA_DELETE_TOPIC_ENABLE: 'true'
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.1.2
    hostname: zookeeper-1
    container_name: zookeeper-1
    restart: always
    ports:
      - "2181:2181"
      - "2180:2180"
    networks:
      - confluent
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_JMX_HOSTNAME: zookeeper-1
      ZOOKEEPER_JMX_PORT: 2180
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"

  kafka-1:
    image:  confluentinc/cp-enterprise-kafka:7.1.2
    hostname: kafka-1
    container_name: kafka-1
    restart: always
    depends_on:
      - zookeeper-1
    ports:
      - "19092:19092"
      - "10091:10091"
    networks:
      - confluent
    environment:
      <<: *broker-common-settings
      KAFKA_BROKER_ID: 101
      # listeners
      KAFKA_LISTENERS: DOCKER://:9092,HOST://:19092
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-1:9092,HOST://kafka-1:19092
      # jmx
      KAFKA_JMX_HOSTNAME: kafka-1
      KAFKA_JMX_PORT: 10091

  kafka-2:
    image:  confluentinc/cp-enterprise-kafka:7.1.2
    hostname: kafka-2
    container_name: kafka-2
    restart: always
    depends_on:
      - zookeeper-1
    ports:
      - "29092:29092"
      - "20091:20091"
    networks:
      - confluent
    environment:
      <<: *broker-common-settings
      KAFKA_BROKER_ID: 102
      # listeners
      KAFKA_LISTENERS: DOCKER://:9092,HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-2:9092,HOST://kafka-2:29092
      # jmx
      KAFKA_JMX_HOSTNAME: kafka-2
      KAFKA_JMX_PORT: 20091

  kafka-3:
    image:  confluentinc/cp-enterprise-kafka:7.1.2
    hostname: kafka-3
    container_name: kafka-3
    restart: always
    depends_on:
      - zookeeper-1
    ports:
      - "39092:39092"
      - "30091:30091"
    networks:
      - confluent
    environment:
      <<: *broker-common-settings
      KAFKA_BROKER_ID: 103
      # listeners
      KAFKA_LISTENERS: DOCKER://:9092,HOST://:39092
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka-3:9092,HOST://kafka-3:39092
      # jmx
      KAFKA_JMX_HOSTNAME: kafka-3
      KAFKA_JMX_PORT: 30091
  
  
  eos:
    networks:
      - confluent
    build: ./
    environment:
      KAFKA_BOOTSTRAP_SERVER: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
      KAFKA_TOPIC: topic-test
      KAFKA_GROUP_ID: consumer-transaction-group
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
        
networks:
  confluent: